---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop calculator-app
      ignore_errors: yes

      
    - name: remove stopped container
      command: docker rm calculator-app
      ignore_errors: yes


    - name: remove used image
      command: docker rmi calculator-app
      ignore_errors: yes


    - name: Running tests
      command: python3 -m unittest test_app.py


    - name: build docker image from dockerfile
      command: docker build -t calculator-app .


    - name: create tag to image
      command: docker tag calculator-app:latest emadeldin1/calculator-flask


    - name: push image to dockerhub
      command: docker push emadeldin1/calculator-flask:latest 


    - name: run container from image
      command: docker run -d -p 8000:8000 calculator-app

      
      #don't forget to docker login to docker hub 