name: continuous integration 

on: [ push ]

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Running tests
        run: python3 -m unittest test_app.py
       

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:

          playbook: ansible-playbook.yml

      